### PR TITLE
Added a new rhyme: the Queen of hearts

### PR DESCRIPTION
**Pull request by mkorman**
I think you're going to _really_ like this one.

Also, notice my clever use of **markdown**

### CODE REVIEW

**Comment by mkorman** [comment]
I _can't wait_ for you to accept this one!

**Comment by mkorman** [comment]
Feeling so excited that I'm overusing exclamation marks!!!!!

**Comment by mkorman** [comment]
Oh, we got emoji too! :+1:

**Comment by mkorman** [comment]
@robcoward @seankearon did you get my request?

**Comment by robcoward** [comment]
Wow, love it :shipit:

**Comment by mkorman** [comment]
Ooooh my first pull request ever has been accepted. Feeling happy :+1:  :100: :8ball:

**Pull request merged**
